name: Build with pnpm run build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pnpm-run-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16, 20.0]

    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: pnpm install --frozen-lockfile
    - run: pnpm run build
